### ISSUE TITLE
[reference] Reorganize reference folder

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-vision#103]
@frgfm, regarding your comment:
https://github.com/pyronear/pyro-vision/pull/101#pullrequestreview-588353780

Maybe we should reorganize the reference folder too, we can split it by tast (classification, detection ...) as it is done in holocron

Then we can specify the dataset in a leaderbord

**Comment by frgfm** [comment]
Yup, fully agree with you :ok_hand:
I can confirm this make things much easier for quick implementation/training cycles!

**Comment by MateoLostanlen** [comment]
Ok I will make the changes, tomorrow
