### ISSUE TITLE
pytorch and torchvision compiled for ARM processor

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-vision#113]
## 🚀 Feature

Add a version of pytorch and torchvision packages compiled for ARM processor

## Motivation

To date, the pyronear prototypes are made of raspberry pi, composed of ARM processors. 
torch and torchvision, required to use pyro-vision package are not compiled for ARM processors. 

## Pitch

It would be great to have those available from pyro-vision (versions of packages available according to pyro-vision release and versions used). 

Also, it would be great to have a tutorial to get to the compiled versions of these packages. 

Thanks a lot and happy to discuss this issue !

**Comment by frgfm** [comment]
As discussed, I think it's a good idea and that we'll put the builds in the release attachments of this package!
I'll make a fresh build for the latest pytorch & torchvision releases this weekend :runner:

**Comment by fe51** [comment]
Great ! Thanks a lot !

**Comment by frgfm** [comment]
Hey there,
Sorry about the delay!

I created a Wiki page over here: https://github.com/pyronear/pyro-vision/wiki/ARM-builds-of-PyTorch-&-Torchvision
And added the ARM wheels in the previous release of this repo:
**PyTorch**
- v1.6.0: https://github.com/pyronear/pyro-vision/releases/download/v0.1.1/torch-1.6.0a0+68f23d5-cp37-cp37m-linux_armv7l.whl
- v1.7.0: https://github.com/pyronear/pyro-vision/releases/download/v0.1.1/torch-1.7.0a0-cp37-cp37m-linux_armv7l.whl
**Torchvision**
- v0.7.0: https://github.com/pyronear/pyro-vision/releases/download/v0.1.1/torchvision-0.7.0a0+34810c0-cp37-cp37m-linux_armv7l.whl
- v0.8.0: https://github.com/pyronear/pyro-vision/releases/download/v0.1.1/torchvision-0.8.0-cp37-cp37m-linux_armv7l.whl

I didn't build the most recent versions yet but I doubt it would be blocking in anyway for now!

**Comment by fe51** [comment]
Hello FG ! Thanks a lot !
We are going to test it as soon as possible !

Yes, most recent versions are not necessary as long as we are able to use pyro-vision :)

FWI @chloeskt :)

**Comment by frgfm** [comment]
Closing the issue as the uploads resolved it and https://github.com/pyronear/pyro-sys-setup/pull/4 is handling integration!
