### ISSUE TITLE
Issue downloading OpenFire

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-vision#118]
## 🐛 Bug

This test do not pass anymore : 

We have a problem with OpenFire, the links to the images work less and less.

Now this test doesn't work anymore:
https://github.com/pyronear/pyro-vision/blob/db08df721c0e563117bded71c71b87b3f1d23b3a/test/test_datasets.py#L103

In the past we have already increased the threshold from 15 to 20 to get around this problem.

I propose to do it again with a big margin, let's take 30.

On the other hand we have to absolutely store this dataset somewhere soon and change the download mode.

**Comment by frgfm** [comment]
Closed by #153
