### ISSUE TITLE
Prediction issues with pyronear/rexnet1_3x

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-vision#166]
### Bug description

It seems that there is a problem with the new [pyronear/rexnet1_3x](https://huggingface.co/pyronear/rexnet1_3x/tree/main) model, the predictions are not very good. It predicts a score of 14% for the [mock_wildfire_image](https://github.com/pyronear/pyro-vision/releases/download/v0.1.2/fire_sample_image.jpg) used in [pyro-engie tests](https://github.com/pyronear/pyro-engine/actions/runs/3118991393/jobs/5058661384#step:6:210), which makes the test that expects an image with fire/smoke to fail.

`FAILED tests/test_engine_core.py::test_engine_offline - assert 0 == 1`

### Code snippet to reproduce the bug

```
hub_repo = "pyronear/rexnet1_3x"
_path =  hf_hub_download(hub_repo, filename="config.json")
with open(_path, "rb") as f:
    cfg = json.load(f)

_path = hf_hub_download(hub_repo, filename="model.onnx")
ort_session = onnxruntime.InferenceSession(_path)

# Load image

url = "https://github.com/pyronear/pyro-vision/releases/download/v0.1.2/fire_sample_image.jpg"
mock_wildfire_stream = requests.get(url).content
img = Image.open(BytesIO(mock_wildfire_stream))
img = img.resize(cfg["input_shape"][-2:], Image.BILINEAR)
print("img size", img.size)
# (H, W, C) --> (C, H, W)
img = np.asarray(img).transpose((2, 1, 0)).astype(np.float32) / 255
# Normalization
img -= np.array(cfg["mean"])[:, None, None]
img /= np.array(cfg["std"])[:, None, None]
ort_input = {ort_session.get_inputs()[0].name: img[None, ...]}
ort_out = ort_session.run(None, ort_input)
# Sigmoid
print(1 / (1 + np.exp(-ort_out[0][0])))
```

### Error traceback

`FAILED tests/test_engine_core.py::test_engine_offline - assert 0 == 1`

### Environment

Collecting environment information...
Pyrovision version: 0.1.2.dev0+ce4db67
PyTorch version: 1.12.1+cu102
Torchvision version: 0.13.1+cu102

OS: Ubuntu 20.04.4 LTS

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Ti Laptop GPU
Nvidia driver version: 512.72
cuDNN version: Could not collect

**Comment by frgfm** [comment]
I think this was due to the resizing issue in pyro-engine ;)

The performance report in pyrovision is accessible over there: https://github.com/pyronear/pyro-vision/blob/master/references/classification/results.csv 

And with the image that you showed, on the demo (using ONNX similarly to the API & Engine), I get 100% confidence on the mock image :+1:

**Comment by MateoLostanlen** [comment]
Ok my bad then
