### ISSUE TITLE
[references] Add unittests or CI checks for training scripts on reduced dataset

### ISSUE THREAD

**Issue by blenzi** [pyronear/pyro-vision#24]
## 🚀 Feature
Add unittests or CI checks for training scripts

## Motivation

Currently one has to test the scripts manually. The dataset is too large to allow a complete test so one idea is to do the training on a reduced one, to be defined.

**Comment by frgfm** [comment]
I suggest considering having a trainer class like in https://github.com/frgfm/Holocron/tree/master/holocron/trainer, which can be unittested but keep the training script untested simply to avoid CI minutes running away too fast!

Closing this for now as we're gonna change the repo general setup shortly, feel free to reopen if you think it's still relevant!
