### ISSUE TITLE
[datasets] Add multi-label classification annotations to OpenFire

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-vision#44]
## 🚀 Feature
Add multi-classification targets to `OpenFire` dataset.

## Motivation

Currently, `OpenFire` only contains binary classification target, which is not enough to reach production-ready performances. Extending the target to multi-label will help reaching better model performances.

## Pitch

The JSON file with annotations will have to be updated with including targets for multiple task:
- binary classification: single boolean value per sample (True notifying the presence of a fire)
- multi-label classification: a few options
1. list of present class per sample (eg. `['class1', 'class3']`)
2. list of present class indices per samples (eg. `[0, 2]`)
3. one-hot encoded vector of present classes (eg. `[True, False, True, ...]`)

**Comment by frgfm** [comment]
@blenzi I'd like your opinion on this. Do you think we should move forward with this? Or discard it?

I was about to close it, but I wondered whether it might still be good to have a multi-label classification dataset (OpenFire or WildFire, or another).

**Comment by blenzi** [comment]
Thanks for looking into this @frgfm. I have the impression this would not be extremely useful for the OpenFire dataset. If I understand correctly it requires new annotations, which will take long to complete. Maybe you want to wait some more results on WildFire to decide?

**Comment by frgfm** [comment]
Agreed, good idea!

**Comment by frgfm** [comment]
Considering latest training results by @MateoLostanlen are quite encouraging, and that the decision to have a multi-label dataset can only be made based on what has been annotated, I'm closing the issue for now.

Feel free to reopen if you disagree
