### ISSUE TITLE
No matching distribution found for pyrovision

### ISSUE THREAD

**Issue by TekayaNidham** [pyronear/pyro-vision#88]
## To Reproduce

```shell
pip install pyrovision
```
output:
```shell
  Collecting pyrovision
  Could not find a version that satisfies the requirement pyrovision (from versions: )
  No matching distribution found for pyrovision

```
- Tested with pip 19.0 and 20.3.3

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pyronear/PyroNear/master/pyro-vision/utils/collect_env.py)
(or fill out the checklist below manually).

 - PyTorch Version (e.g., 1.2): 1.7.1
 - Torchvision Version (e.g., 0.4): 0.8.2
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Python version:3.6

**Comment by frgfm** [comment]
Thanks for reporting this!
Since the package was renamed, the next release will fix this :+1:

**Comment by frgfm** [comment]
Latest release has been uploaded to pypi : https://pypi.org/project/pyrovision/
