### ISSUE TITLE
[models] Module design suggestion

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-vision#93]
Here is a suggestion for the `pyrovision.models` module's organization:
- utils.py: shared utility functions
- XYZ.py: classification architecture definion with pretrained weights
- detection: folder with the definition of object detection models with pretrained weights
- segmentation: folder with the definition of segmentation models with pretrained weights

All performances of pretrained versions should be reported either in the documentation, the readme or a readme in the references folder.

**Comment by MateoLostanlen** [comment]
I don't understand your point here, we already have this architecture. We only have classification models. You want to add empty detection and segmentation folders?

**Comment by frgfm** [comment]
It was to plan the incoming additions to the library

**Comment by MateoLostanlen** [comment]
ok sure let's do that

**Comment by frgfm** [comment]
My bad, I haven't cleaned up the classification models! I'll do this by the end of the weekend

**Comment by frgfm** [comment]
Closed by #138 & #150
